#!/bin/bash

## INSTALL SCRIPT
## -------------

# Installs yeet to your computer

## CREDITS
# ASCII art using the figlet CLI from AUR (https://aur.archlinux.org/packages/figlet) and the pagga font from the figlet-fonts-extra package from AUR (https://aur.archlinux.org/packages/figlet-fonts-extra_)

## DEPENDENCIES
# This script uses the following extra commands:
# - pacman
# - wget
# - sudo (base-devel)
# - makepkg (base-devel)

## SETUP
# Unalias everything to prevent weirdness
unalias -a
# Fail and exit when the first error occurs
set -e
# For debbuging
#set -xv

## UTILITY
# Print messages in colour
# Green text
function printg {
	echo -e "\e[1;32m$*\e[0m"
}
# Blue text
function printb {
	echo -e "\e[1;34m$*\e[0m"
}
# Yellow text
function printw {
	echo -e "\e[1;33m$*\e[0m"
}
# Red text
function printr {
	echo -e "\e[1;31m$*\e[0m"
}

## UI
# Print out the logo (generated using command `figlet -f pagga YEET`)
printw ""
printw "░░░░░░░░░░░░░░░░░"
printw "░█░█░█▀▀░█▀▀░▀█▀░"
printw "░░█░░█▀▀░█▀▀░░█░░"
printw "░░▀░░▀▀▀░▀▀▀░░▀░░"
printw "░░░░░░░░░░░░░░░░░"
printw ""
printw "v0.1.0"
printw ""

# Check if they are on arch linux
platform=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$platform" in
	"linux") printg " ==> Platform detected: linux" && printw " ==> Please ensure you are installing ONLY ON ARCH LINUX. This script may fail or cause CATASTROPHIC damage if run on other distros.";;
	*) printr " ERR Unsupported platform \`$platform\`; only linux/macos is supported for now."; exit 1;;
esac

# Check if `git` is installed
if ! [ -f $(command -v git) ] ; then
	printr " ERR Command git not found, please install git using \`pacman -S git\` first"
	exit 1
fi
# Check if `base-devel` is installed
if ! [ -f $(command -v makepkg) ] ; then
	printr " ERR Group base-devel not found, please install base-devel using \`pacman -S base-devel\` first"
	exit 1
fi

# Start building
printg " ==> Starting build process..."

# The build dir is the same as if we were installing yeet using yeet
mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/yeet/build/yeet/"
cd "${XDG_CACHE_HOME:-$HOME/.cache}/yeet/build/yeet/"
git clone https://aur.archlinux.org/yeet.git
cd yeet
makepkg -sic

# No need to print any message after install, the postinstall function already takes care of that
printb ""
